FROM golang:1.22-alpine as build

RUN apk --no-cache add curl

ENV ENV=production

WORKDIR /go/src/app

COPY . .

RUN curl -O https://git.io/GeoLite2-City.mmdb

RUN go build -o ip .

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1

CMD ["./ip"]
