FROM golang:1.22-alpine as build

RUN apk --no-cache add curl wget

WORKDIR /go/src/app

COPY . .

RUN wget https://git.io/GeoLite2-City.mmdb

RUN go build -o ip .

FROM alpine:latest

ENV ENV=production

WORKDIR /app

COPY --from=build /go/src/app/ip /app/ip

COPY --from=build /go/src/app/GeoLite2-City.mmdb /app/GeoLite2-City.mmdb

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1

CMD ["./ip"]
